import stockimg from '../Assests/teslaimg.jpeg';

const DataCar = [
  {
    id: 1,
    img:  stockimg ,
    type: "Sedan",
    company: "Tesla",
    fuel: "Petrol",
    capacity: "1 Suitcase",
    transmition: "Auto",
    price: "£250",
  },
  {
    id: 2,
    img:  stockimg ,
    type: "Sedan",
    company: "Honda",
    fuel: "Petrol",
    capacity: "2 Suitcase",
    transmition: "Auto",
    price: "£390",
  },
  {
    id: 3,
    img:  stockimg ,
    type: "Sedan",
    company: "Cultus",
    fuel: "Petrol",
    capacity: "9 Suitcase",
    transmition: "Manuel",
    price: "£750",
  },
  {
    id: 4,
    img: stockimg ,
    type: "Sedan",
    company: "Mehran",
    fuel: "Petrol",
    capacity: "1 Suitcase",
    transmition: "Manuel",
    price: "£910",
  },
  {
    id: 5,
    img:  stockimg ,
    type: "Sedan",
    company: "Mazda",
    fuel: "Petrol",
    capacity: "1 Suitcase",
    transmition: "Auto",
    price: "£8450",
  },
  {
    id: 6,
    img:  stockimg ,
    type: "Sedan",
    company: "Swift",
    fuel: "Petrol",
    capacity: "9 Suitcase",
    transmition: "Auto",
    price: "£1250",
  },
];

export default DataCar;
